In [1]:
import numpy as np

# Numpy Basics

# Numpy Arrays

## Array initialization

In [6]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
type(arr1), arr1.shape, arr1.dtype

(numpy.ndarray, (2, 3), dtype('int32'))

In [8]:
arr1.min(), arr1.max(), arr1.mean(), arr1.std(), arr1.sum()

(1, 6, 3.5, 1.707825127659933, 21)

In [3]:
arr2 = np.zeros((2, 3), dtype=int)
arr2

array([[0, 0, 0],
       [0, 0, 0]])

In [10]:
arr3 = np.ones((2, 3), order='c')
arr3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
arr4 = np.full((5, 2), 9)
arr4

array([[9, 9],
       [9, 9],
       [9, 9],
       [9, 9],
       [9, 9]])

In [19]:
arr_identity = np.eye(5, 4, k=2)
arr_identity

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
arr_square = np.identity(5)
arr_square

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Arrays from data

In [35]:
np.arange(1, 10, 2) #정수 범위 

array([1, 3, 5, 7, 9])

In [36]:
np.linspace(0, 1, 5) #실수 범위

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [37]:
np.logspace(0, 1, 5) #로그 스케일 범위

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

## np.random

In [ ]:
np.random.seed(42)

In [29]:
arr_random = np.random.random_sample((2, 3))
arr_random

array([[0.80009616, 0.95467522, 0.41693272],
       [0.91593202, 0.63860823, 0.35696858]])

In [32]:
arr_random_int = np.random.randint(0, 10, (2, 3))
arr_random_int

array([[2, 6, 7],
       [4, 3, 7]])

In [38]:
arr_random_normal = np.random.normal(0, 1, (2, 3))
arr_random_normal

array([[-0.58087813, -0.52516981, -0.57138017],
       [-0.92408284, -2.61254901,  0.95036968]])

## Array Indexing

In [40]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
arr1[0], arr1[1]

(array([1, 2, 3]), array([4, 5, 6]))

In [42]:
arr1[0, 0], arr1[0, 1], arr1[1, 0]

(1, 2, 4)

In [43]:
arr1[0][0], arr1[0][1], arr1[1][0]

(1, 2, 4)

In [48]:
arr1[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [14]:
arr1[arr1 > 2]

array([3, 4, 5, 6])

## Array Reshape

`.T`/`.transpose()` 메소드는 전치행렬을 구한다.

In [17]:
arr1.T, arr1.transpose()

(array([[1, 4],
        [2, 5],
        [3, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

`.flatten()` 메소드는 다차원 배열을 1차원으로 평탄화시킬 때 사용한다.

In [18]:
arr1.flatten()

array([1, 2, 3, 4, 5, 6])

`.ravel()` 메소드는 배열의 shape를 1차원으로 만들 때 사용한다.

In [50]:
arr1.ravel()

array([1, 2, 3, 4, 5, 6])

In [58]:
arr2 = np.arange(20)
arr2.reshape(4, 5) # 사이즈 맞춰야 오류 없음

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [61]:
arr2.resize(4, 5) # 사이즈 맞춰야 오류 없음
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

`np.resize` 함수는 변화 결과 원소 수를 줄이거나 늘일 수 있다. `np.reshape`는 그렇지 않아, 사이즈를 맞추지 않으면 오류가 발생한다.

In [62]:
np.resize(arr2, (2, 7))

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [63]:
np.reshape(arr2, (2, 7))

ValueError: cannot reshape array of size 20 into shape (2,7)

## Array data append/delete

### `.append()`

## Array Calculations

In [19]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

In [21]:
arr1 + arr2, np.add(arr1, arr2)

(array([[ 8, 10, 12],
        [14, 16, 18]]),
 array([[ 8, 10, 12],
        [14, 16, 18]]))

In [22]:
arr1 - arr2, np.subtract(arr1, arr2)

(array([[-6, -6, -6],
        [-6, -6, -6]]),
 array([[-6, -6, -6],
        [-6, -6, -6]]))

In [24]:
arr1 * arr2, np.multiply(arr1, arr2) # element-wise multiplication

(array([[ 7, 16, 27],
        [40, 55, 72]]),
 array([[ 7, 16, 27],
        [40, 55, 72]]))

In [25]:
arr1 / arr2, np.divide(arr1, arr2) # element-wise division

(array([[0.14285714, 0.25      , 0.33333333],
        [0.4       , 0.45454545, 0.5       ]]),
 array([[0.14285714, 0.25      , 0.33333333],
        [0.4       , 0.45454545, 0.5       ]]))

In [31]:
arr1.dot(arr2.T) # matrix multiplication/dot product

array([[ 50,  68],
       [122, 167]])

집계 연산 시 axis를 기준으로 계산된다. axis 지정 않으면 None이다. 

axis = 0에서는 각 행 그룹을 집계 함수로, axis = 1에서는 각 열 그룹을 집계 함수로 요약한다.

In [49]:
arr1.sum(), arr1.sum(axis=0), arr1.sum(axis=1)

(21, array([5, 7, 9]), array([ 6, 15]))

## Broadcasting

브로드캐스팅 : 행렬 크기가 달라도 연산 가능하도록 작은 행렬 확장.
배수 사이즈 행렬이어야 가능.

In [28]:
arr3 = np.array([[1, 2, 3]])
arr1 + arr3

array([[2, 4, 6],
       [5, 7, 9]])

# Numpy Functions